# Generated by Django 4.1.5 on 2024-02-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcontact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='Contact',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
